version: '3.7'
services:
    app:
        container_name: 'ocs_inventory'
        restart: always
        build: .
        ports:
            - 8080:80
        depends_on:
            - db
        command: tail -f /dev/null 
    db:
        image: mariadb
        container_name: 'db-compose'
        restart: always
        environment:
            MYSQL_DATABASE: 'ocsweb'
            MYSQL_USER: "${DB_MYSQL_USER}"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
